[tool.poetry]
name = "quickbook-connector"
version = "0.1.0"
description = "QuickBooks Connector for Misc Income synchronization"
authors = ["Parikshith Saraswathi <psarasw@purude.edu> Eduardo Araujo <araujoe@purdue.edu>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
openpyxl = ">=3.1.5,<4.0.0"
pywin32 = ">=311,<312"

[tool.poetry.group.dev.dependencies]
pre-commit = ">=4.3.0,<5.0.0"
ruff = ">=0.14.0,<0.15.0"
mypy = ">=1.18.2,<2.0.0"
pytest = ">=8.4.2,<9.0.0"
pytest-coverage = ">=0.0,<0.1"
pyinstaller = ">=6.16.0,<7.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
qb-connector = "src.__main__:main"
